# Generated by Django 4.2.27 on 2026-01-07 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.CharField(help_text='Unique card identifier', max_length=50)),
                ('door_name', models.CharField(help_text='Name of the door', max_length=100)),
                ('access_granted', models.BooleanField(help_text='Whether access was granted')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When the log was created')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
